Repository CodingOnTeamBook/Rebook_React_Node, pull requests merged in 2021-07, with the labels that each got.

#57 Change review detail/issue/#50
  client/src/App.tsx
  client/src/components/PeopleComponent/SelectGenreTag.tsx
  client/src/components/ReviewComponent/AddComment.tsx
  client/src/components/ReviewComponent/BookInfo.tsx
  client/src/components/ReviewComponent/ReviewMain.tsx
  client/src/components/ReviewComponent/ReviewModal.tsx
  client/src/components/ReviewComponent/SelectSort.tsx
  client/src/components/ReviewComponent/UserReview.tsx
  client/src/components/ReviewDetailComponent/AddComment.tsx
  client/src/components/ReviewDetailComponent/BookInfo.tsx
  client/src/components/ReviewDetailComponent/CommentList.tsx
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  client/src/pages/ReviewPage/index.tsx
Labels: enhancement, frontend

#61 People detail page/issue/#51
  client/src/App.tsx
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/PeopleDetialComponent/UserInfo.tsx
  client/src/components/ReviewComponent/ReviewMain.tsx
  client/src/components/ReviewDetailComponent/BookInfo.tsx
  client/src/pages/PeopleDetailPage/index.tsx
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewPage/index.tsx
Labels: enhancement, frontend

#52 Nickname check/issue/#46
  .env
  .gitignore
  client/package-lock.json
  client/src/config.example.ts
  client/yarn.lock
  config/config.json
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/book/book.controller.ts
  server/src/book/book.module.ts
  server/src/book/book.service.ts
  server/src/config/db.config.example.ts
  server/src/config/jwt.config.example.ts
  server/src/entities/comment.entity.ts
  server/src/entities/genre.entity.ts
  server/src/entities/like.entity.ts
  server/src/entities/review.entity.ts
  server/src/entities/tag.entity.ts
  server/src/entities/user.entity.ts
  server/src/reviews/dto/create-review.dto.ts
  server/src/reviews/dto/update-review.dto.ts
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.module.ts
  server/src/reviews/reviews.service.ts
  server/src/users/auth.middleware.ts
  server/src/users/entities/user.entity.ts
  server/src/users/error.middleware.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
  server/src/users/users.service.ts
Labels: backend, enhancement

#67 New write page mark up issue#60
  client/package-lock.json
  client/package.json
  client/src/components/WriteReviewComponent/TagsInput.tsx
  client/src/components/WriteReviewComponent/WriteEditor.tsx
  client/src/components/common/BookDetail.tsx
  client/src/pages/BookDetailPage/index.tsx
  client/src/pages/WriteReviewPage/index.tsx
  client/yarn.lock
  server/package-lock.json
Labels: enhancement, frontend

#65 Feature/myinfo reviews/issue/#58
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: backend, enhancement

#76 Modify review review detail/issue/#73
  client/package-lock.json
  client/src/components/ReviewComponent/ReviewMain.tsx
  client/src/components/ReviewDetailComponent/AddComment.tsx
  client/src/components/ReviewDetailComponent/BookInfo.tsx
  client/src/components/ReviewDetailComponent/CommentList.tsx
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  package-lock.json
  server/package-lock.json
Labels: bug, frontend

#74 Review writeand detail/issue/#56
  server/src/app.module.ts
  server/src/entities/genre.entity.ts
  server/src/entities/review.entity.ts
  server/src/entities/user.entity.ts
  server/src/main.ts
  server/src/reviews/dto/create-review.dto.ts
  server/src/reviews/dto/update-review.dto.ts
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.multerOptions.ts
  server/src/reviews/reviews.service.ts
  server/src/users/auth.middleware.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
  server/src/users/users.multerOptions.ts
  server/src/users/users.service.ts
  server/uploads/review/test.html
  server/uploads/users/test.JPG
Labels: backend, enhancement

#81 Transfer date function/issue/#77
  client/src/components/ReviewComponent/ReviewMain.tsx
  client/src/components/ReviewDetailComponent/BookInfo.tsx
  client/src/components/ReviewDetailComponent/CommentList.tsx
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/components/myPage/MyComment.tsx
  client/src/globalFunction/TransferDate.ts
  client/src/pages/PeopleDetailPage/index.tsx
  client/src/pages/ReviewDetailPage/index.tsx
Labels: enhancement, frontend

#83 Interpark api/issue/#79
  server/src/book/book.controller.ts
  server/src/book/book.service.ts
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.service.ts
  server/src/users/error.middleware.ts
Labels: backend, enhancement

#84 Mypage default value/issue/#78
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/PeopleDetialComponent/UserInfo.tsx
  client/src/components/ReviewDetailComponent/BookInfo.tsx
  client/src/components/myPage/MyInfo.tsx
  client/src/globalFunction/myInfoDefaultValue.ts
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  client/src/style/img/user (1).png
  client/src/style/img/user.png
Labels: enhancement, frontend

#82 Landing page to search page
  client/src/App.tsx
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/PopulateReviews.tsx
  client/src/components/ReviewComponent/ReviewMain.tsx
  client/src/components/ReviewDetailComponent/AddComment.tsx
  client/src/components/ReviewDetailComponent/BookInfo.tsx
  client/src/components/ReviewDetailComponent/CommentList.tsx
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/components/SearchForm.tsx
  client/src/components/SignUpContainer.tsx
  client/src/components/common/BookInfo.tsx
  client/src/components/common/KaKaoLoginBtn.tsx
  client/src/components/common/LandingPageCommon.tsx
  client/src/components/myPage/SmallReview.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/redux/rootReducer.ts
  client/src/redux/search/action.ts
  client/src/redux/search/reducer.ts
  client/src/redux/search/search-type.ts
  server/package-lock.json
  server/src/book/book.service.ts
Labels: enhancement, frontend

#92 Bug fix issue#91
  client/package-lock.json
  client/src/pages/SearchPage/index.tsx
  client/src/redux/search/action.ts
  client/src/redux/search/reducer.ts
  client/src/redux/search/search-type.ts
  client/yarn.lock
  package-lock.json
Labels: enhancement, frontend

#88 New best seller api#87
  client/src/components/LandingPage/BestSeller.tsx
  client/src/components/LandingPage/CarouselComponent.tsx
  client/src/components/LandingPage/CarouselItem.tsx
  client/src/components/LandingPage/PopulateReviews.tsx
  client/src/components/common/LandingPageCommon.tsx
  client/src/components/common/SearchForm.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  server/src/app.module.ts
  server/src/book/book.controller.ts
Labels: enhancement, frontend

#100 Reviewer/issue/#85
  server/src/app.module.ts
  server/src/book/book.controller.ts
  server/src/entities/comment.entity.ts
  server/src/entities/like.entity.ts
  server/src/entities/review.entity.ts
  server/src/entities/user.entity.ts
  server/src/reviewer/reviewer.controller.ts
  server/src/reviewer/reviewer.module.ts
  server/src/reviewer/reviewer.service.ts
  server/src/reviews/dto/create-review.dto.ts
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.exportFunction.ts
  server/src/reviews/reviews.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: backend, enhancement

#101 New search page to book detail issue#96
  client/src/App.tsx
  client/src/components/BookDetail/ReviewWriteBtn.tsx
  client/src/components/LandingPage/BestSeller.tsx
  client/src/components/common/BookDetail.tsx
  client/src/components/common/BookInfo.tsx
  client/src/pages/BookDetailPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/redux/book/action.ts
  client/src/redux/book/book-type.ts
  client/src/redux/book/reducer.ts
  client/src/redux/rootReducer.ts
  server/src/book/book.service.ts
Labels: enhancement, frontend

#103 bestseller component styling
  client/package-lock.json
  client/src/components/common/LandingPageCommon.tsx
  package-lock.json
  server/package-lock.json
Labels: enhancement, frontend

#107 Bookservice fix
  server/src/book/book.service.ts
  server/src/comments/comments.controller.ts
  server/src/comments/comments.module.ts
  server/src/users/dto/create-user.dto.ts
  server/src/users/users.service.ts
Labels: backend

#104 Review detail get data/issue/#98
  client/src/components/ReviewComponent/ReviewItem.tsx
  client/src/components/ReviewDetailComponent/AddComment.tsx
  client/src/components/ReviewDetailComponent/BookInfo.tsx
  client/src/components/ReviewDetailComponent/CommentList.tsx
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  client/src/pages/ReviewPage/index.tsx
Labels: enhancement, frontend

#108 Review updateand delete/issue/#102
  server/src/reviewer/reviewer.controller.ts
  server/src/reviewer/reviewer.service.ts
  server/src/reviews/dto/update-review.dto.ts
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.exportFunction.ts
  server/src/reviews/reviews.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: backend, enhancement

#111 New book detail page get reviews issue#110
  client/src/components/BookDetail/BookReview.tsx
  client/src/pages/BookDetailPage/index.tsx
Labels: enhancement, frontend

#109 New search page review search issue#95
  client/src/API/REVIEWER_PUBLIC_API/index.ts
  client/src/API/REVIEWER_PUBLIC_API/reviewer.interface.ts
  client/src/API/USER_PUBLIC_API/index.ts
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/common/SearchForm.tsx
  client/src/pages/ReviewPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  server/src/users/users.service.ts
Labels: enhancement, frontend

#115 Person component conflict issue
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/PeopleComponent/Reviewer.tsx
  client/src/pages/SearchPage/index.tsx
Labels: frontend

#112 Reviewer page get data/issue/#105
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/PeopleComponent/SelectGenreTag.tsx
  client/src/pages/PeoplePage/index.tsx
  server/src/app.module.ts
Labels: enhancement, frontend

#122 Modify review/write/issue/#113
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/comments/comments.service.ts
  server/src/comments/dto/create-comment.dto.ts
  server/src/entities/comment.entity.ts
  server/src/reviewer/reviewer.controller.ts
  server/src/reviewer/reviewer.service.ts
  server/src/reviews/dto/create-review.dto.ts
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.exportFunction.ts
  server/src/reviews/reviews.multerOptions.ts
  server/src/reviews/reviews.service.ts
  server/src/users/dto/update-user.dto.ts
  server/src/users/users.controller.ts
  server/src/users/users.multerOptions.ts
  server/src/users/users.service.ts
Labels: backend, enhancement

#121 Fix book detail component isuue#120
  client/src/components/BookDetail/BookDetail.tsx
  client/src/components/BookDetail/BookReview.tsx
  client/src/components/LandingPage/BestSeller.tsx
  client/src/components/common/BookDetail.tsx
  client/src/pages/BookDetailPage/index.tsx
Labels: enhancement, frontend

#119 New review write page
  client/src/API/USER_PRIVATE_API/user.interface.ts
  client/src/components/BookDetail/ReviewWriteBtn.tsx
  client/src/components/WriteReviewComponent/StarRate.tsx
  client/src/components/WriteReviewComponent/SubmitBtn.tsx
  client/src/components/WriteReviewComponent/TagsInput.tsx
  client/src/components/WriteReviewComponent/ToggleBtn.tsx
  client/src/components/WriteReviewComponent/WriteEditor.tsx
  client/src/components/common/KaKaoLoginBtn.tsx
  client/src/pages/BookDetailPage/index.tsx
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewPage/index.tsx
  client/src/pages/WriteReviewPage/index.tsx
  server/src/app.module.ts
  server/uploads/review/유진_1627028322868.txt
Labels: enhancement, frontend, question

#124 리뷰 페이지, 리뷰어 페이지 무한 스크롤
  client/package-lock.json
  client/package.json
  client/src/components/PeopleComponent/Person.tsx
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  client/src/pages/ReviewPage/index.tsx
  package-lock.json
Labels: enhancement, frontend, question

#127 Fix review page bug issue#125
  client/src/components/BookDetail/BookReview.tsx
  client/src/components/WriteReviewComponent/WriteEditor.tsx
  client/src/modules/book/action.ts
  client/src/pages/BookDetailPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  server/src/reviews/reviews.service.ts
Labels: backend, enhancement, frontend

#128 [UPDATE] fix api/review/detail, return profileImgUrl
  server/src/reviewer/reviewer.service.ts
  server/src/reviews/reviews.exportFunction.ts
  server/src/reviews/reviews.service.ts
  server/src/users/dto/create-user.dto.ts
  server/src/users/users.multerOptions.ts
  server/src/users/users.service.ts
Labels: backend, bug, enhancement

#136 api/users/updateImg
  server/src/users/users.controller.ts
  server/src/users/users.multerOptions.ts
  server/src/users/users.service.ts
Labels: backend, enhancement

#140 마이페이지에서 프로필사진이 로드되지 않는 현상 fix
  server/src/users/users.service.ts
Labels: backend

#142 Review Detail Page html file load
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  server/src/reviews/reviews.service.ts
  server/uploads/review/리북씨_1627125433323.html
  server/uploads/review/리북씨_1627125489362.html
  server/uploads/review/리북씨_1627125566592.html
  server/uploads/review/리북씨_1627125978936.html
  server/uploads/review/안녕_1627195275141.html
  server/uploads/review/유진_1627028322868.html
Labels: enhancement, frontend, question

#150 머지 재시도
  server/src/reviewer/reviewer.service.ts
  server/src/reviews/reviews.exportFunction.ts
  server/src/reviews/reviews.multerOptions.ts
  server/src/reviews/reviews.service.ts
  server/src/users/users.service.ts
Labels: backend

#149 [FIX] mypage getMyLikes fix
  server/.gitignore
  server/src/users/users.service.ts
Labels: backend, enhancement

#141 mypage 작업
  Untitled Diagram.drawio
  client/package-lock.json
  client/package.json
  client/src/API/USER_PRIVATE_API/index.ts
  client/src/API/USER_PRIVATE_API/user.interface.ts
  client/src/components/LandingPage/PopulateReviews.tsx
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/components/SignUpContainer.tsx
  client/src/components/common/Header.tsx
  client/src/components/myPage/CommentBox.tsx
  client/src/components/myPage/FollowReviewer.tsx
  client/src/components/myPage/LikeReview.tsx
  client/src/components/myPage/MenuIconBtn.tsx
  client/src/components/myPage/MyInfo.tsx
  client/src/components/myPage/MyReview.tsx
  client/src/components/myPage/SmallReview.tsx
  client/src/components/myPage/sideMenu.tsx
  client/src/hooks/useInput.ts
  client/src/pages/LandingPage/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/WriteReviewPage/index.tsx
  server/package-lock.json
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.service.ts
  server/src/users/dto/update-user.dto.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
  server/uploads/review/안녕_1627169241048.txt
  server/uploads/review/안녕_1627169259352.txt
  server/uploads/review/안녕_1627169388574.txt
  server/uploads/review/안녕_1627169428067.txt
  server/uploads/review/안녕_1627170175593.txt
  server/uploads/review/안녕_1627177908106.txt
  server/uploads/review/안녕_1627177926395.txt
  server/uploads/review/안녕_1627177946368.txt
  server/uploads/review/안녕_1627177973907.txt
  server/uploads/review/안녕_1627177992087.txt
  server/uploads/review/안녕_1627177997624.txt
  server/uploads/review/안녕_1627178012524.txt
  server/uploads/review/안녕_1627189374646.txt
  server/uploads/review/안녕_1627189445500.txt
  server/uploads/review/안녕_1627189470324.txt
  server/uploads/review/안녕_1627189502030.txt
Labels: frontend

#152 Review like/issue/143
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  server/uploads/review/리북씨_1627209077541.html
  server/uploads/review/리북씨_1627209132552.html
  server/uploads/review/리북씨_1627209150333.html
Labels: enhancement, frontend

#159 Like reivew detail fix/issue/#155
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  server/uploads/review/승미니_1627289248316.html
  server/uploads/review/승미니_1627292493134.html
  server/uploads/review/승미니_1627297848249.html
  server/uploads/review/승미니_1627308111114.html
  server/uploads/review/승미니_1627308115337.html
Labels: enhancement, frontend

#158 Update landing page modify issue#157
  client/src/App.tsx
  client/src/components/LandingPage/BestSeller.tsx
  client/src/components/LandingPage/PopulateReviews.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/LandingPageCommon.tsx
  client/src/components/common/ScrollToTop.tsx
  client/src/components/myPage/SmallReview.tsx
  client/src/globalFunction/fetchData.ts
  client/src/pages/LandingPage/index.tsx
Labels: bug, enhancement, frontend

#161 Update search page issue#160
  client/package-lock.json
  client/package.json
  client/src/components/LandingPage/BestSeller.tsx
  client/src/components/LandingPage/PopulateReviews.tsx
  client/src/components/common/SearchForm.tsx
  client/src/globalFunction/fetchData.ts
  client/src/pages/LandingPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/yarn.lock
  server/uploads/review/제주위트에일_1627324028769.html
  server/uploads/review/제주위트에일_1627375682211.html
  server/uploads/review/제주위트에일_1627377348566.html
  server/uploads/review/제주위트에일_1627377813064.html
Labels: enhancement, frontend

#164 Review enhancement/issue/#154
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/ReviewComponent/ReviewItem.tsx
  client/src/components/ReviewDetailComponent/UserReview.tsx
  client/src/globalFunction/myInfoDefaultValue.ts
  client/src/globalFunction/shortInfo.ts
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewDetailPage/index.tsx
  client/src/pages/ReviewPage/index.tsx
  server/src/reviews/reviews.service.ts
  server/uploads/review/승미니_1627447771159.html
  server/uploads/review/승미니_1627447808982.html
  server/uploads/review/승미니_1627447843380.html
  server/uploads/review/승미니_1627448114096.html
  server/uploads/review/승미니_1627453540149.html
  server/uploads/review/승미니_1627491813124.html
Labels: enhancement, frontend

#168 Fix1
  server/.gitignore
  server/package.json
  server/src/app.module.ts
  server/src/logger.ts
  server/src/main.ts
  server/src/reviewer/reviewer.service.ts
  server/src/reviews/dto/update-review.dto.ts
  server/src/reviews/reviews.controller.ts
  server/src/reviews/reviews.module.ts
  server/src/users/auth.middleware.ts
  server/src/users/dto/create-user.dto.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
Labels: backend
