Repository CodingOnTeamBook/Rebook_React_Node, pull requests merged in 2021-06, with the labels that each got.

#5 Design, Dir Setting
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/Header.tsx
  client/src/pages/BookDetailPage/index.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SignupPage/index.tsx
  client/src/pages/WriteReviewPage/index.tsx
  client/src/style/componentStyled.tsx
  client/src/style/globalStyles.tsx
  client/src/style/img/logo.png
  client/src/style/styled.d.ts
  client/src/style/theme.ts
Labels: enhancement

#18 리뷰, 태그 모델 세팅 완료/issue/#6
  .gitignore
  app.js
  models/index.js
  models/review.js
  models/tag.js
  package-lock.json
  package.json
Labels: backend, enhancement

#16 Login hooks/issue/#13
  client/src/App.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/ProfileModal.tsx
  client/src/pages/BookDetailPage/index.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/RecommendBookPage/index.tsx
  client/src/pages/ReviewPage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SignupPage/index.tsx
  client/src/pages/WriteReviewPage/index.tsx
  client/src/style/componentStyled.tsx
Labels: enhancement, frontend

#21 SignUpPage Markup, state 설정
  client/package-lock.json
  client/src/components/CheckBoxGroupComponent.tsx
  client/src/components/SignUpContainer.tsx
  client/src/components/UserNameFormComponent.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/SignupPage/index.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement, frontend

#26 Kakao login/issue/#14
  app.js
  client/package-lock.json
  client/package.json
  client/src/components/common/Header.tsx
  client/src/components/common/KaKaoLoginBtn.tsx
  client/src/components/common/LoginModalContents.tsx
  client/src/components/common/ProfileModal.tsx
  client/src/hooks/USER_API/index.ts
  client/src/index.tsx
  client/src/redux/index.ts
  client/src/redux/user/AuthReducer.ts
  client/src/redux/user/type.ts
  models/genre.js
  models/index.js
  models/review.js
  models/tag.js
  models/user.js
  package-lock.json
Labels: enhancement

#30 Landing Page - Input Component 작성
  client/src/components/SearchForm.tsx
  client/src/pages/LandingPage/index.tsx
Labels: frontend

#32 customHook and Ref
  client/src/components/CheckBoxGroupComponent.tsx
  client/src/components/SignUpContainer.tsx
  client/src/components/UserNameFormComponent.tsx
  client/src/components/common/LoginModalContents.tsx
  client/src/components/common/SimpleModal.tsx
  client/src/components/defaultData/genre.ts
  client/src/hooks/useCheck.ts
  client/src/hooks/useInput.ts
  client/src/index.tsx
Labels: enhancement, frontend

#36 Review page/issue/#34
  client/src/components/ReviewComponent/BookInfo.tsx
  client/src/components/ReviewComponent/ReviewMain.tsx
  client/src/pages/ReviewPage/index.tsx
Labels: enhancement, frontend

#37 New landing page popular section mark up#35
  client/package-lock.json
  client/src/components/PopularBooks.tsx
  client/src/components/common/LoginModalContents.tsx
  client/src/pages/LandingPage/index.tsx
  client/yarn.lock
Labels: enhancement, frontend

#41 로그아웃 구현
  .eslintrc
  .prettierrc
  app.js
  models/user.js
  package-lock.json
  package.json
  passport/index.js
  passport/localStrategy.js
  route/auth.js
  route/index.js
  route/middlewares.js
  route/users.js
Labels: backend, enhancement

#47 People page/issue/#38
  client/src/components/PeopleComponent/Person.tsx
  client/src/components/PeopleComponent/SelectGenreTag.tsx
  client/src/components/ReviewComponent/ReviewMain.tsx
  client/src/components/ReviewComponent/ReviewModal.tsx
  client/src/components/ReviewComponent/SelectSort.tsx
  client/src/components/common/GridItem.tsx
  client/src/components/common/GridLayout.tsx
  client/src/pages/PeoplePage/index.tsx
  client/src/pages/ReviewPage/index.tsx
  package-lock.json
Labels: enhancement, frontend

#44 New landing page popular reviews#40
  client/models/index.js
  client/src/components/PopulateReviews.tsx
  client/src/components/RecommendedBooks.tsx
  client/src/components/common/LandingPageCommon.tsx
  client/src/pages/LandingPage/index.tsx
Labels: enhancement, frontend

#49 mypage markup
  client/package.json
  client/src/App.tsx
  client/src/components/CheckBoxGroupComponent.tsx
  client/src/components/common/LoginModalContents.tsx
  client/src/components/myPage/FollowReviewer.tsx
  client/src/components/myPage/LikeReview.tsx
  client/src/components/myPage/MyComment.tsx
  client/src/components/myPage/MyInfo.tsx
  client/src/components/myPage/MyReview.tsx
  client/src/components/myPage/sideMenu.tsx
  client/src/pages/MyPage/index.tsx
  client/src/setupProxy.ts
  client/src/style/componentStyled.tsx
  server/package-lock.json
  server/package.json
Labels: enhancement
